# Generated by Django 6.0.2 on 2026-02-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_contact_contact_subject_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='date',
        ),
    ]
